version: '3'
services:
  api:
    build:
      context: .
    environment:
      - MONGO_URI=mongodb://notSecretUsername:notSecretPassword@mongodb
    ports:
      - 3001:3001
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=notSecretUsername
      - MONGO_INITDB_ROOT_PASSWORD=notSecretPassword